export const OVERVIEW = 'Overview'
export const BENIFITS = 'Benifits'
export const SERVICES = 'Services'
export const EXPERTISE = 'Expertise'
export const METHODOLOGY = 'Methodology'
export const CONTACT_US = 'Contact Us'
